generators:
  php: "ClientGenerator.php"

repos:
  core:
    name: "MCSDK-Automation-Framework-Core"
    owner: "salesforce-marketingcloud"
    swagger_cli: "{%repos_core_dir%}/bin/swagger-codegen-cli-2.4.7.jar"
    swagger_spec: "{%repos_core_dir%}/resources/sfmc-openapi-v2.json"
    composer_cli: "{%repos_core_dir%}/bin/composer.phar"
  sdk:
    name: "MCSDK-Automation-PHP"
    owner: "salesforce-marketingcloud"
    packageName: "SalesForce"
    tests:
      - "php-sdk-api"
      - "php-sdk-auth"
